services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bingo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - .docker/redis:/data
